### PR TITLE
Move NavLayout styles to utils/styles

### PR DESCRIPTION
**Pull request by cmjosephs**
Screen Shot 2022-03-19 at 10 28 05 AM
Screen Shot 2022-03-19 at 10 28 48 AM

Moved the file containing the CSS for the Side and Top NavBars to utils/styles. Changed the import line in components/NavLayout/[NavLayout, TopBar, SideBar] to reflect these module's new location in the folder structure.

### CODE REVIEW

**Comment by cmjosephs** [comment]
@Atlantic-Software-Consulting/classmates-devs  Please review PR

**Review by kevinhwkim — COMMENTED** [review]
Looks good

**Comment by tiffanyyv** [comment]
Looks good

**Comment by TristenUrban** [comment]
Looks good, this new file structure should help the team keep everything looking clean!

**Review by mtchang25 — COMMENTED** [review]
LTGM

**Pull request merged**
